name: Good Job
on: [push]
jobs:

  build:
    name: Test
    runs-on: ${{ matrix.vm-os }}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        vm-os: [ubuntu-latest]
        go-version: [1.13.5]
        # vm-os: [ubuntu-latest, macOS-latest, windows-latest]
        # go-version: [1.11.13, 1.12.13, 1.13.4]

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      shell: bash
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build & Run
      shell: bash
      run: |
        make build
        ./md5con 5000000

    - name: Mount Disk
      shell: bash
      run: |
        df -h
        free -h
        ls -lash /mnt
        mkdir -p /mnt/ramdisk
        mount -t tmpfs -o size=512m tmpfs /mnt/ramdisk
        df -h
        ls -lash /mnt/ramdisk
        cp md5con /mnt/ramdisk
        ls -lash /mnt/ramdisk
